name: Pending Approvals

on:
  pull_request_target:
    types: [opened, synchronize, labeled]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  pending-approvals:
    name: Check Pending Approvals
    continue-on-error: true
    runs-on: ubuntu-latest
    if: >-
      (
        github.event_name == 'pull_request_target' &&
        github.event.action == 'opened'
      ) || (
        github.event_name == 'pull_request_target' &&
        (github.event.action == 'labeled' || github.event.action == 'synchronize') &&
        contains(github.event.pull_request.labels.*.name, 'verified')
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.comment.body == 'pending_reviews' &&
        github.event.issue.pull_request != null
      )
    steps:
      - name: Install actions-ci
        run: npm install -g @sidj-thr/actions-ci@0.5.0

      - name: Check PR approvals
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_APP_ID: ${{ secrets.APP_ID }}
          GITHUB_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
        run: |
          actions-ci pending-approvals \
            --pr-number "${{ github.event.pull_request.number || github.event.issue.number }}" \
            --maintainers-team 'qvac-mgmt' \
            --team-leads-team 'qvac-internal-merge' \
            --min-approvals '2'
